name             'deploy-systemview'
maintainer       'OSU Open Source Lab'
maintainer_email 'systems@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures systemview'
long_description 'Installs/Configures systemview'
version          '0.1.0'

depends 'python'
depends 'git'
depends 'gunicorn'
depends 'supervisor'
depends 'nginx'
